### ISSUE TITLE
I got this error!

### ISSUE THREAD

**Issue by wanesta** [drcut/FFM-tensorflow#3]
WARNING:tensorflow:Variable += will be deprecated. Use variable.assign_add if you want assignment to the variable value or 'x = x + y' if you want a new python Tensor object.
Traceback (most recent call last):
  File "FFM.py", line 143, in <module>
    ffm = FFM(batch_size, learning_rate, data_path, field_num, feature_num, feature_map, data_set)
  File "FFM.py", line 83, in __init__
    W1 = tf.nn.embedding_lookup(self.field_embedding[f1], self.feature2field[f2])
KeyError: 11

**Comment by 15801851637** [comment]
I also want to know why this error occurs.....

**Comment by fabs2017** [comment]
me too.how to solve this error?
